In [379]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [485]:
def convolution(image,kernel):
    num_rows,num_cols,num_channels = image.shape
    rows = np.array([j+(i*num_cols)+ (num_cols*num_rows*k) for k in range(num_channels) for i in range(kernel.shape[0]) for j in range(kernel.shape[1])])
    cols = np.array([j+(i*num_cols) for i in range(kernel.shape[0]) for j in range(num_cols-kernel.shape[1]+1)])
    grid = rows[None,:]+cols[:,None]
    image_tr = image.transpose(2,0,1)
    kernel_tr = kernel.transpose(2,0,1)
    conv = np.dot(image_tr.take(grid),kernel_tr.flatten())
    out_h,out_w = (image.shape[0]-kernel.shape[0]+1),(image.shape[1]-kernel.shape[1]+1)
    conv = conv.reshape(out_h,out_w)
    return conv

In [486]:
image = np.random.randint(0,255,size=(5,5,3))
kernel = np.random.uniform(size=(3,3,3))
conv = convolution(image,kernel)
print(conv)

[[2081.1512677  2117.01453457 2212.48515403]
 [1571.95827338 1775.61020793 2083.8907313 ]
 [1668.02857244 2009.01944184 2248.85617642]]


In [487]:
image = np.random.randint(0,255,size=(2,5,5,3))

In [488]:
def convolution2(image,kernel):
    mb,num_rows,num_cols,num_channels = image.shape
    rows = np.array([j+(i*num_cols)+ (num_cols*num_rows*k) for k in range(num_channels) for i in range(kernel.shape[0]) for j in range(kernel.shape[1])])
    cols = np.array([j+(i*num_cols) for i in range(kernel.shape[0]) for j in range(num_cols-kernel.shape[1]+1)])
    grid = rows[None,:]+cols[:,None]
    batch = np.array(range(0,mb)) * num_channels * num_rows*num_cols
    grid = batch[:,None,None] + grid[None,:,:]
    image_tr = image.transpose(0,3,1,2)
    kernel_tr = kernel.transpose(2,0,1)
    conv = np.dot(image_tr.take(grid),kernel_tr.flatten())
    out_h,out_w = (image.shape[1]-kernel.shape[0]+1),(image.shape[2]-kernel.shape[1]+1)
    conv = conv.reshape(mb,out_h,out_w)
    return conv

In [489]:
convolution2(image,kernel)

array([[[1586.73350667, 1480.20435651, 1870.01848184],
        [1537.84870637, 1768.58135831, 1850.60109807],
        [1965.2304619 , 2146.43063633, 1836.08809354]],

       [[1755.05862728, 1870.55574524, 2295.26092165],
        [1870.33668479, 1987.89334248, 2257.9251233 ],
        [1971.89085547, 1752.5401403 , 1821.83708129]]])

#### Idea from -> https://sgugger.github.io/convolution-in-depth.html#convolution-in-depth